/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace MockSettlement {
  export type IntentStruct = {
    id: string;
    maker: AddressLike;
    sellToken: AddressLike;
    buyToken: AddressLike;
    sellAmount: BigNumberish;
    minBuyAmount: BigNumberish;
    deadline: BigNumberish;
  };

  export type IntentStructOutput = [
    id: string,
    maker: string,
    sellToken: string,
    buyToken: string,
    sellAmount: bigint,
    minBuyAmount: bigint,
    deadline: bigint
  ] & {
    id: string;
    maker: string;
    sellToken: string;
    buyToken: string;
    sellAmount: bigint;
    minBuyAmount: bigint;
    deadline: bigint;
  };
}

export interface MockSettlementInterface extends Interface {
  getFunction(nameOrSignature: "amms" | "settle"): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "IntentFulfilled" | "SettlementExecuted"
  ): EventFragment;

  encodeFunctionData(functionFragment: "amms", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "settle",
    values: [MockSettlement.IntentStruct, MockSettlement.IntentStruct]
  ): string;

  decodeFunctionResult(functionFragment: "amms", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "settle", data: BytesLike): Result;
}

export namespace IntentFulfilledEvent {
  export type InputTuple = [
    intentId: string,
    maker: AddressLike,
    amountReceived: BigNumberish
  ];
  export type OutputTuple = [
    intentId: string,
    maker: string,
    amountReceived: bigint
  ];
  export interface OutputObject {
    intentId: string;
    maker: string;
    amountReceived: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementExecutedEvent {
  export type InputTuple = [totalProfit: BigNumberish];
  export type OutputTuple = [totalProfit: bigint];
  export interface OutputObject {
    totalProfit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockSettlement extends BaseContract {
  connect(runner?: ContractRunner | null): MockSettlement;
  waitForDeployment(): Promise<this>;

  interface: MockSettlementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  amms: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  settle: TypedContractMethod<
    [
      intentA: MockSettlement.IntentStruct,
      intentB: MockSettlement.IntentStruct
    ],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "amms"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "settle"
  ): TypedContractMethod<
    [
      intentA: MockSettlement.IntentStruct,
      intentB: MockSettlement.IntentStruct
    ],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "IntentFulfilled"
  ): TypedContractEvent<
    IntentFulfilledEvent.InputTuple,
    IntentFulfilledEvent.OutputTuple,
    IntentFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "SettlementExecuted"
  ): TypedContractEvent<
    SettlementExecutedEvent.InputTuple,
    SettlementExecutedEvent.OutputTuple,
    SettlementExecutedEvent.OutputObject
  >;

  filters: {
    "IntentFulfilled(string,address,uint256)": TypedContractEvent<
      IntentFulfilledEvent.InputTuple,
      IntentFulfilledEvent.OutputTuple,
      IntentFulfilledEvent.OutputObject
    >;
    IntentFulfilled: TypedContractEvent<
      IntentFulfilledEvent.InputTuple,
      IntentFulfilledEvent.OutputTuple,
      IntentFulfilledEvent.OutputObject
    >;

    "SettlementExecuted(uint256)": TypedContractEvent<
      SettlementExecutedEvent.InputTuple,
      SettlementExecutedEvent.OutputTuple,
      SettlementExecutedEvent.OutputObject
    >;
    SettlementExecuted: TypedContractEvent<
      SettlementExecutedEvent.InputTuple,
      SettlementExecutedEvent.OutputTuple,
      SettlementExecutedEvent.OutputObject
    >;
  };
}
